import { NextRequest, NextResponse } from "next/server";
import { createClient } from "@/lib/supabase-server";

export async function GET(req: NextRequest) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Not logged in" }, { status: 401 });

  const friendId = req.nextUrl.searchParams.get("friendId");
  if (!friendId) return NextResponse.json({ error: "friendId required" }, { status: 400 });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({
      recommendation: "AI recommendations are not configured. Add ANTHROPIC_API_KEY to enable this feature.",
    });
  }

  const [myProfile, friendProfile, myResult, theirResult] = await Promise.all([
    supabase.from("profiles").select("username, display_name").eq("id", user.id).single(),
    supabase.from("profiles").select("username, display_name").eq("id", friendId).single(),
    supabase.from("items").select("category, title, creator, rank").eq("user_id", user.id).order("rank"),
    supabase.from("items").select("category, title, creator, rank").eq("user_id", friendId).order("rank"),
  ]);

  const myName = myProfile.data?.display_name || myProfile.data?.username || "You";
  const friendName = friendProfile.data?.display_name || friendProfile.data?.username || "Friend";
  const myItems = myResult.data || [];
  const theirItems = theirResult.data || [];

  const formatList = (items: { rank: number; category: string; title: string; creator: string }[]) =>
    items.map((i) => `${i.rank}. [${i.category}] ${i.title}${i.creator ? ` by ${i.creator}` : ""}`).join("\n");

  const prompt = `You're a cultural taste analyst. Two friends have shared their favorite books, films, and TV shows. Analyze their taste overlap and make recommendations.

${myName}'s ranked favorites:
${formatList(myItems) || "(no items yet)"}

${friendName}'s ranked favorites:
${formatList(theirItems) || "(no items yet)"}

Please:
1. Briefly describe what they have in common (shared tastes, genres, themes)
2. Note interesting differences in their taste
3. Recommend 3-5 specific titles from ${friendName}'s list that ${myName} might enjoy, explaining why
4. Recommend 3-5 titles NOT on either list that both might enjoy together

Keep it conversational and fun. Use their names. Be specific about why you're recommending things.

Note: These recommendations are generated by AI (Claude) based on the titles in each person's list. The AI doesn't have access to any other personal data.`;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5-20250929",
        max_tokens: 1024,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const data = await res.json();
    const text = data.content?.[0]?.text || "Could not generate recommendations.";
    return NextResponse.json({ recommendation: text });
  } catch (err) {
    return NextResponse.json({
      recommendation: `Could not generate AI recommendations: ${err instanceof Error ? err.message : "Unknown error"}`,
    });
  }
}
