import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { getCurrentUser } from "@/lib/auth";

interface ItemRow {
  category: string;
  title: string;
  creator: string;
  rank: number;
}

export async function GET(req: NextRequest) {
  const user = await getCurrentUser();
  if (!user) return NextResponse.json({ error: "Not logged in" }, { status: 401 });

  const friendId = req.nextUrl.searchParams.get("friendId");
  if (!friendId) return NextResponse.json({ error: "friendId required" }, { status: 400 });

  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) {
    return NextResponse.json({
      recommendation: "AI recommendations are not configured. Add ANTHROPIC_API_KEY to your .env.local file to enable this feature.",
    });
  }

  const db = getDb();

  const friend = db.prepare("SELECT username, display_name FROM users WHERE id = ?").get(friendId) as { username: string; display_name: string };
  const myItems = db.prepare("SELECT category, title, creator, rank FROM items WHERE user_id = ? ORDER BY category, rank").all(user.id) as ItemRow[];
  const theirItems = db.prepare("SELECT category, title, creator, rank FROM items WHERE user_id = ? ORDER BY category, rank").all(friendId) as ItemRow[];

  const friendName = friend.display_name || friend.username;

  const formatList = (items: ItemRow[]) =>
    items.map((i) => `${i.rank}. [${i.category}] ${i.title}${i.creator ? ` by ${i.creator}` : ""}`).join("\n");

  const prompt = `You're a cultural taste analyst. Two friends have shared their favorite books, films, and TV shows. Analyze their taste overlap and make recommendations.

${user.display_name || user.username}'s ranked favorites:
${formatList(myItems) || "(no items yet)"}

${friendName}'s ranked favorites:
${formatList(theirItems) || "(no items yet)"}

Please:
1. Briefly describe what they have in common (shared tastes, genres, themes)
2. Note interesting differences in their taste
3. Recommend 3-5 specific titles from ${friendName}'s list that ${user.display_name || user.username} might enjoy, explaining why based on their existing taste
4. Recommend 3-5 titles NOT on either list that both might enjoy together

Keep it conversational and fun. Use their names. Be specific about why you're recommending things.

Note: These recommendations are generated by AI (Claude) based on the titles in each person's list. The AI doesn't have access to any other personal data.`;

  try {
    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-sonnet-4-5-20250929",
        max_tokens: 1024,
        messages: [{ role: "user", content: prompt }],
      }),
    });

    const data = await res.json();
    const text = data.content?.[0]?.text || "Could not generate recommendations.";

    return NextResponse.json({ recommendation: text });
  } catch (err) {
    return NextResponse.json({
      recommendation: `Could not generate AI recommendations: ${err instanceof Error ? err.message : "Unknown error"}`,
    });
  }
}
